[package]
name = "dsa"
version = "1.0.0"
authors = ["Jo√£o Russo <r0u6s12s18o@gmail.com>"]
edition = "2018"
license = "MIT"
description = " Solutions to various coding problems"

[dependencies]
md5 = "0.7.0"
regex = "1.11.1"
clap = { version = "4.5.54", features = ["derive"] }
